[versions]
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
serializationJson = "1.9.0"
navigation = "2.9.6"
lifecycleKtxRuntime = "2.10.0"
agp = "8.12.3"
kotlin = "2.2.21"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
timber = "5.0.1"
dagger = "2.57.2"
datastorePreferences = "1.2.0"
composeRuntime = "1.9.4"
navigationCompose = "2.9.6"
kotlin-ksp = "2.3.2"
hiltNavigationCompose = "1.2.0"
coroutines = "1.9.0"
systemUiController = "0.36.0"
roomKtx = "2.8.4"
webkit = "1.14.0"
geckoview = "144.0.20251027123126"
composeIcons = "1.1.1"
media = "1.7.0"

junit4 = "4.13.2"
junit5 = "5.10.2"
androidxTest = "1.7.0"
androidxJunit = "1.3.0"
espresso = "3.7.0"
coroutinesTest = "1.10.2"
mockk = "1.14.7"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref= "serializationJson" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleKtxRuntime" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
system-ui-controller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "systemUiController" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomKtx" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomKtx" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
geckoview = { group = "org.mozilla.geckoview", name = "geckoview", version.ref = "geckoview" }
composeicon-feather = { group = "br.com.devsrsouza.compose.icons", name = "feather", version.ref = "composeIcons" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "media" }
# Local unit test
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
junit-vintage = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit5" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

# Android instrumented test
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTest" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger"}
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }

